version: '3.4'
name: 'wms'

services:
  wms.api:
    container_name: wms_api
    image: ${DOCKER_REGISTRY-}wmsapi
    build:
      context: .
      dockerfile: WMS.Api/Dockerfile
  
  wms.write.db:
    image: postgres:latest
    container_name: write_db
    environment:
      POSTGRES_DB: wms_write_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Swordfish123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wms.read.db:
    image: mysql:latest
    container_name: read_db
    environment:
      MYSQL_ROOT_PASSWORD: Swordfish123
      MYSQL_DATABASE: wms_read_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  db.synchro.queue:
    image: "rabbitmq:3.9-management"
    container_name: synchro_queue
    ports:
      - "5672:5672"  # RabbitMQ standard AMQP port
      - "15672:15672"  # RabbitMQ management plugin's web UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Swordfish123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mysql_data:
  rabbitmq_data:  