version: '3.4'
name: 'wms'

services:
  wms.api:
    container_name: wms_api
    image: ${DOCKER_REGISTRY-}wmsapi
    build:
      context: .
      dockerfile: WMS.Api/Dockerfile
  
  wmd.write.db:
    image: postgres:latest
    container_name: write_db
    environment:
      POSTGRES_DB: wms_write_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Swordfish123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: read_db
    environment:
      MYSQL_ROOT_PASSWORD: Swordfish123
      MYSQL_DATABASE: wms_read_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data: